name: Htn79
favicon: null
layout_spectrum: 0.34053
typography_spectrum: 0.5257788
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ffffff'
    - '#d7ab14'
    - '#000000'
    - '#de1305'
    - '#5d54a6'
  brandStrength: 1
  lightness: 0
  saturation: 0
  rhythmicContrast: 1
purpose: []
