layout_spectrum: 0.2271751
color:
  saturation: 1
  brandStrength: 0
  lightness: 0
  brandColors:
    - '#F7FCF6'
    - '#6E5443'
    - '#D1D7D7'
    - '#141418'
    - '#323743'
  rhythmicContrast: 1
typography_spectrum: 0.5257788
name: Htn79
